<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>《餐饮服务食品安全监督管理办法》学习</title>
    <link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/static/bootstrap/css/bootstrap.min.css">
</head>
<body style="background-color:steelblue">
<div style="position: fixed;right: 0px;width:8%;background: whitesmoke"><h3>本次学习时间：</h3><h2 id="time">0</h2></div>
<div style="margin-top: 2%; margin-left: 10%; margin-right: 10%; background-color:whitesmoke; padding-left: 3%; padding-right: 3%; padding-top: 3%">
    <div>
        <div class="concent" id="zoom">
            <div class="title" id="zoomtitl"><ucmstitle>餐饮服务食品安全监督管理办法（卫生部令第71号）</ucmstitle></div>
            <div class="title2" id="zoomtitl"></div>
            <div class="ftitle" id="zoomtime">中华人民共和国卫生部&nbsp;&nbsp;&nbsp;&nbsp;www.moh.gov.cn&nbsp;&nbsp;&nbsp;&nbsp;
            </div>
            <div id="zoomsubtitl"></div>




            <!--按站点检索稿件时用别删-->
            <!--<ucmssource>政策法规司</ucmssource>-->
            <div class="con_font" id="contentzoom"> 　　
                <ucmscontent><P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><?xml:namespace prefix = o ns = "urn:schemas-microsoft-com:office:office" /><o:p>&nbsp;</o:p></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">《餐饮服务食品安全监督管理办法》已于<?xml:namespace prefix = st1 ns = "urn:schemas-microsoft-com:office:smarttags" /><st1:chsdate Year="2010" Month="2" Day="8" IsLunarDate="False" IsROCDate="False" w:st="on"><SPAN lang=EN-US>2010</SPAN>年<SPAN lang=EN-US>2</SPAN>月<SPAN lang=EN-US>8</SPAN>日</st1:chsdate>经卫生部部务会议审议通过，现予以发布，自<st1:chsdate Year="2010" Month="5" Day="1" IsLunarDate="False" IsROCDate="False" w:st="on"><SPAN lang=EN-US>2010</SPAN>年<SPAN lang=EN-US>5</SPAN>月<SPAN lang=EN-US>1</SPAN>日起</st1:chsdate>施行。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 272pt; mso-char-indent-count: 17.0"><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><o:p>&nbsp;</o:p></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 272pt; mso-char-indent-count: 17.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">部<SPAN lang=EN-US><SPAN style="mso-spacerun: yes">&nbsp;&nbsp; </SPAN></SPAN>长<SPAN lang=EN-US><SPAN style="mso-spacerun: yes">&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN>陈<SPAN lang=EN-US><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN>竺<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 272pt; mso-char-indent-count: 17.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">二○一○年<st1:chsdate Year="2010" Month="3" Day="4" IsLunarDate="False" IsROCDate="False" w:st="on">三月四日</st1:chsdate><SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align=center><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><o:p>&nbsp;</o:p></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align=center><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第一章<SPAN lang=EN-US><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN>总<SPAN lang=EN-US><SPAN style="mso-spacerun: yes">&nbsp;&nbsp;&nbsp; </SPAN></SPAN>则<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第一条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">为加强餐饮服务监督管理，保障餐饮服务环节食品安全，根据《中华人民共和国食品安全法》（以下简称《食品安全法》）、《中华人民共和国食品安全法实施条例》（以下简称《食品安全法实施条例》），制定本办法。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第二条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">在中华人民共和国境内从事餐饮服务的单位和个人（以下简称餐饮服务提供者）应当遵守本办法。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第三条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">国家食品药品监督管理局主管全国餐饮服务监督管理工作，地方各级食品药品监督管理部门负责本行政区域内的餐饮服务监督管理工作。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第四条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">餐饮服务提供者应当依照法律、法规、食品安全标准及有关要求从事餐饮服务活动，对社会和公众负责，保证食品安全，接受社会监督，承担餐饮服务食品安全责任。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第五条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">鼓励社会团体、基层群众性自治组织开展餐饮服务食品安全知识和相关法律、法规的普及工作，增强餐饮服务提供者食品安全意识，提高消费者自我保护能力；鼓励开展技术服务工作，促进餐饮服务提供者提高食品安全管理水平。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">餐饮服务相关行业协会应当加强行业自律，引导餐饮服务提供者依法经营，推动行业诚信建设，宣传、普及餐饮服务食品安全知识。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第六条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">鼓励和支持餐饮服务提供者为提高食品安全水平而采用先进技术和先进的管理规范，实施危害分析与关键控制点体系，配备先进的食品安全检测设备，对食品进行自行检查或者向具有法定资质的机构送检。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第七条<SPAN lang=EN-US><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">任何组织和个人均有权对餐饮服务食品安全进行社会监督，举报餐饮服务提供者违反本办法的行为，了解有关餐饮服务食品安全信息，对餐饮服务食品安全工作提出意见和建议。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt"><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><o:p>&nbsp;</o:p></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align=center><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第二章<SPAN lang=EN-US><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN>餐饮服务基本要求<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第八条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">餐饮服务提供者必须依法取得《餐饮服务许可证》，按照许可范围依法经营，并在就餐场所醒目位置悬挂或者摆放《餐饮服务许可证》。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第九条<SPAN lang=EN-US><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">餐饮服务提供者应当建立健全食品安全管理制度，配备专职或者兼职食品安全管理人员。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">被吊销《餐饮服务许可证》的单位，根据《食品安全法》第九十二条的规定，其直接负责的主管人员自处罚决定作出之日起<SPAN lang=EN-US>5</SPAN>年内不得从事餐饮服务管理工作。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">餐饮服务提供者不得聘用本条前款规定的禁止从业人员从事管理工作。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第十条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">餐饮服务提供者应当按照《食品安全法》第三十四条的规定，建立并执行从业人员健康管理制度，建立从业人员健康档案。餐饮服务从业人员应当依照《食品安全法》第三十四条第二款的规定每年进行健康检查，取得健康合格证明后方可参加工作。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">从事直接入口食品工作的人员患有《食品安全法实施条例》第二十三条规定的有碍食品安全疾病的，应当将其调整到其他不影响食品安全的工作岗位。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第十一条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">餐饮服务提供者应当依照《食品安全法》第三十二条的规定组织从业人员参加食品安全培训，学习食品安全法律、法规、标准和食品安全知识，明确食品安全责任，并建立培训档案；应当加强专（兼）职食品安全管理人员食品安全法律法规和相关食品安全管理知识的培训。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第十二条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">餐饮服务提供者应当建立食品、食品原料、食品添加剂和食品相关产品的采购查验和索证索票制度。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">餐饮服务提供者从食品生产单位、批发市场等采购的，应当查验、索取并留存供货者的相关许可证和产品合格证明等文件；从固定供货商或者供货基地采购的，应当查验、索取并留存供货商或者供货基地的资质证明、每笔供货清单等；从超市、农贸市场、个体经营商户等采购的，应当索取并留存采购清单。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">餐饮服务企业应当建立食品、食品原料、食品添加剂和食品相关产品的采购记录制度。采购记录应当如实记录产品名称、规格、数量、生产批号、保质期、供货者名称及联系方式、进货日期等内容，或者保留载有上述信息的进货票据。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">餐饮服务提供者应当按照产品品种、进货时间先后次序有序整理采购记录及相关资料，妥善保存备查。记录、票据的保存期限不得少于<SPAN lang=EN-US>2</SPAN>年。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第十三条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">实行统一配送经营方式的餐饮服务提供者，可以由企业总部统一查验供货者的许可证和产品合格的证明文件等，建立食品进货查验记录。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">实行统一配送经营方式的，企业各门店应当建立总部统一配送单据台账。门店自行采购的产品，应当遵照本办法第十二条的规定。<SPAN lang=EN-US><SPAN style="mso-spacerun: yes">&nbsp; </SPAN><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第十四条<SPAN lang=EN-US><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">餐饮服务提供者禁止采购、使用和经营下列食品：<SPAN lang=EN-US> <o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（一）《食品安全法》第二十八条规定禁止生产经营的食品；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（二）违反《食品安全法》第四十八条规定的食品；<SPAN lang=EN-US> <o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（三）违反《食品安全法》第五十条规定的食品；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（四）违反《食品安全法》第六十六条规定的进口预包装食品。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第十五条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">餐饮服务提供者应当按照国家有关规定和食品安全标准采购、保存和使用食品添加剂。应当将食品添加剂存放于专用橱柜等设施中，标示“食品添加剂”字样，妥善保管，并建立使用台账。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第十六条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">餐饮服务提供者应当严格遵守国家食品药品监督管理部门制定的餐饮服务食品安全操作规范。餐饮服务应当符合下列要求：<SPAN lang=EN-US> <o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（一）在制作加工过程中应当检查待加工的食品及食品原料，发现有腐败变质或者其他感官性状异常的，不得加工或者使用；<SPAN lang=EN-US> <o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（二）贮存食品原料的场所、设备应当保持清洁，禁止存放有毒、有害物品及个人生活物品，应当分类、分架、隔墙、离地存放食品原料，并定期检查、处理变质或者超过保质期限的食品；<SPAN lang=EN-US> <o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（三）应当保持食品加工经营场所的内外环境整洁，消除老鼠、蟑螂、苍蝇和其他有害昆虫及其孳生条件；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（四）应当定期维护食品加工、贮存、陈列、消毒、保洁、保温、冷藏、冷冻等设备与设施，校验计量器具，及时清理清洗，确保正常运转和使用；<SPAN lang=EN-US> <o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（五）操作人员应当保持良好的个人卫生；<SPAN lang=EN-US> <o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（六）需要熟制加工的食品，应当烧熟煮透；需要冷藏的熟制品，应当在冷却后及时冷藏；应当将直接入口食品与食品原料或者半成品分开存放，半成品应当与食品原料分开存放；<SPAN lang=EN-US> <o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（七）制作凉菜应当达到专人负责、专室制作、工具专用、消毒专用和冷藏专用的要求；<SPAN lang=EN-US><SPAN style="mso-spacerun: yes">&nbsp;&nbsp; </SPAN><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（八）用于餐饮加工操作的工具、设备必须无毒无害，标志或者区分明显，并做到分开使用，定位存放，用后洗净，保持清洁；接触直接入口食品的工具、设备应当在使用前进行消毒；<SPAN lang=EN-US><SPAN style="mso-spacerun: yes">&nbsp; </SPAN><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（九）应当按照要求对餐具、饮具进行清洗、消毒，并在专用保洁设施内备用，不得使用未经清洗和消毒的餐具、饮具；购置、使用集中消毒企业供应的餐具、饮具，应当查验其经营资质，索取消毒合格凭证；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（十）应当保持运输食品原料的工具与设备设施的清洁，必要时应当消毒。运输保温、冷藏（冻）食品应当有必要的且与提供的食品品种、数量相适应的保温、冷藏（冻）设备设施。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第十七条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">食品药品监督管理部门依法开展抽样检验时，被抽样检验的餐饮服务提供者应当配合抽样检验工作，如实提供被抽检样品的货源、数量、存货地点、存货量、销售量、相关票证等信息。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt"><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><o:p>&nbsp;</o:p></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align=center><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第三章<SPAN lang=EN-US><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN>食品安全事故处理<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第十八条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">各级食品药品监督管理部门应当根据本级人民政府食品安全事故应急预案制定本部门的预案实施细则，按照职能做好餐饮服务食品安全事故的应急处置工作。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第十九条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">食品药品监督管理部门在日常监督管理中发现食品安全事故，或者接到有关食品安全事故的举报，应当立即核实情况，经初步核实为食品安全事故的，应当立即向同级卫生行政、农业行政、工商行政管理、质量监督等相关部门通报。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">发生食品安全事故时，事发地食品药品监督管理部门应当在本级人民政府领导下，及时做出反应，采取措施控制事态发展，依法处置，并及时按照有关规定向上级食品药品监督管理部门报告。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第二十条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">县级以上食品药品监督管理部门按照有关规定开展餐饮服务食品安全事故调查，有权向有关餐饮服务提供者了解与食品安全事故有关的情况，要求餐饮服务提供者提供相关资料和样品，并采取以下措施：<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（一）封存造成食品安全事故或者可能导致食品安全事故的食品及其原料，并立即进行检验；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（二）封存被污染的食品工具及用具，并责令进行清洗消毒；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt"><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN><SPAN style="mso-spacerun: yes">&nbsp;&nbsp;</SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（三）经检验，属于被污染的食品，予以监督销毁；未被污染的食品，予以解封；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（四）依法对食品安全事故及其处理情况进行发布，并对可能产生的危害加以解释、说明。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第二十一条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">餐饮服务提供者应当制定食品安全事故处置方案<SPAN lang=EN-US>,</SPAN>定期检查各项食品安全防范措施的落实情况<SPAN lang=EN-US>,</SPAN>及时消除食品安全事故隐患。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第二十二条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">餐饮服务提供者发生食品安全事故，应当立即封存导致或者可能导致食品安全事故的食品及其原料、工具及用具、设备设施和现场，在<SPAN lang=EN-US>2</SPAN>小时之内向所在地县级人民政府卫生部门和食品药品监督管理部门报告，并按照相关监管部门的要求采取控制措施。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">餐饮服务提供者应当配合食品安全监督管理部门进行食品安全事故调查处理，按照要求提供相关资料和样品，不得拒绝。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt"><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><o:p>&nbsp;</o:p></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align=center><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第四章<SPAN lang=EN-US><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN>监督管理<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第二十三条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">食品药品监督管理部门可以根据餐饮服务经营规模，建立并实施餐饮服务食品安全监督管理量化分级、分类管理制度。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">食品药品监督管理部门可以聘请社会监督员，协助开展餐饮服务食品安全监督。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第二十四条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">县级以上食品药品监督管理部门履行食品安全监督职责时，发现不属于本辖区管辖的，应当及时移送有管辖权的食品药品监督管理部门。接受移送的食品药品监督管理部门应当将被移送案件的处理情况及时反馈给移送案件的食品药品监督管理部门。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第二十五条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">县级以上食品药品监督管理部门接到咨询、投诉、举报，对属于本部门管辖的，应当受理，并及时进行核实、处理、答复；对不属于本部门管辖的，应当书面通知并移交有管辖权的部门处理。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">发现餐饮服务提供者使用不符合食品安全标准及有关要求的食品原料或者食用农产品、食品添加剂、食品相关产品，其成因属于其他环节食品生产经营者或者食用农产品生产者的，应当及时向本级卫生行政、农业行政、工商行政管理、质量监督等部门通报。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第二十六条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">食品药品监督管理部门在履行职责时<SPAN lang=EN-US>,</SPAN>有权采取《食品安全法》第七十七条规定的措施。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第二十七条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">食品安全监督检查人员对餐饮服务提供者进行监督检查时，应当对下列内容进行重点检查：<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（一）餐饮服务许可情况；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（二）从业人员健康证明、食品安全知识培训和建立档案情况；<SPAN lang=EN-US> <o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（三）环境卫生、个人卫生、食品用工具及设备、食品容器及包装材料、卫生设施、工艺流程情况；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（四）餐饮加工制作、销售、服务过程的食品安全情况；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（五）食品、食品添加剂、食品相关产品进货查验和索票索证制度及执行情况、制定食品安全事故应急处置制度及执行情况；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（六）食品原料、半成品、成品、食品添加剂等的感官性状、产品标签、说明书及储存条件；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（七）餐具、饮具、食品用工具及盛放直接入口食品的容器的清洗、消毒和保洁情况；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（八）用水的卫生情况；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（九）其他需要重点检查的情况。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第二十八条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">食品安全监督检查人员进行监督检查时，应当有<SPAN lang=EN-US>2</SPAN>名以上人员共同参加，依法制作现场检查笔录，笔录经双方核实并签字。被监督检查者拒绝签字的，应当注明事由和相关情况，同时记录在场人员的姓名、职务等。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第二十九条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">县级以上食品药品监督管理部门负责组织实施本辖区餐饮服务环节的抽样检验工作，所需经费由地方财政列支。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第三十条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">食品安全监督检查人员可以使用经认定的食品安全快速检测技术进行快速检测，及时发现和筛查不符合食品安全标准及有关要求的食品、食品添加剂及食品相关产品。使用现场快速检测技术发现和筛查的结果不得直接作为执法依据。对初步筛查结果表明可能不符合食品安全标准及有关要求的食品，应当依照《食品安全法》的有关规定进行检验。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">快速检测结果表明可能不符合食品安全标准及有关要求的，餐饮服务提供者应当根据实际情况采取食品安全保障措施。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第三十一条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">食品安全监督检查人员抽样时必须按照抽样计划和抽样程序进行，并填写抽样记录。抽样检验应当购买产品样品，不得收取检验费和其他任何费用。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">食品安全监督检查人员应当及时将样品送达有资质的检验机构。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第三十二条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">食品检验机构应当根据检验目的和送检要求，按照食品安全相关标准和规定的检验方法进行检验，按时出具合法的检验报告。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第三十三条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">对检验结论有异议的，异议人有权自收到检验结果告知书之日起<SPAN lang=EN-US>10</SPAN>日内，向组织实施抽样检验的食品药品监督管理部门提出书面复检申请，逾期未提出申请的，视为放弃该项权利。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">复检工作应当选择有关部门共同公布的承担复检工作的食品检验机构完成。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">复检机构由复检申请人自行选择；复检机构与初检机构不得为同一机构。复检机构出具的复检结论为最终检验结论。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">复检费用的承担依《食品安全法实施条例》第三十五条的规定。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第三十四条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">食品药品监督管理部门应当建立辖区内餐饮服务提供者食品安全信用档案，记录许可颁发及变更情况、日常监督检查结果、违法行为查处等情况。食品药品监督管理部门应当根据餐饮服务食品安全信用档案，对有不良信用记录的餐饮服务提供者实施重点监管。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">食品安全信用档案的形式和内容由省级食品药品监督管理部门根据本地实际情况作出具体规定。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第三十五条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">食品药品监督管理部门应当将吊销《餐饮服务许可证》的情况在<SPAN lang=EN-US>7</SPAN>日内通报同级工商行政管理部门。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第三十六条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">县级以上食品药品监督管理部门依法公布下列日常监督管理信息：<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">(</SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">一<SPAN lang=EN-US>)</SPAN>餐饮服务行政许可情况；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">(</SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">二<SPAN lang=EN-US>)</SPAN>餐饮服务食品安全监督检查和抽检的结果；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">(</SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">三<SPAN lang=EN-US>)</SPAN>查处餐饮服务提供者违法行为的情况；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">(</SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">四<SPAN lang=EN-US>)</SPAN>餐饮服务专项检查工作情况；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">(</SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">五<SPAN lang=EN-US>)</SPAN>其他餐饮服务食品安全监督管理信息。<SPAN lang=EN-US> <o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt"><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><o:p>&nbsp;</o:p></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align=center><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第五章<SPAN lang=EN-US><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN>法律责任<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第三十七条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">未经许可从事餐饮服务的，由食品药品监督管理部门根据《食品安全法》第八十四条的规定予以处罚。有下列情形之一的，按未取得《餐饮服务许可证》查处：<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">(</SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">一<SPAN lang=EN-US>)</SPAN>擅自改变餐饮服务经营地址、许可类别、备注项目的；<SPAN lang=EN-US><SPAN style="mso-spacerun: yes">&nbsp;&nbsp;&nbsp; </SPAN><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">(</SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">二<SPAN lang=EN-US>)</SPAN>《餐饮服务许可证》超过有效期限仍从事餐饮服务的；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">(</SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">三<SPAN lang=EN-US>)</SPAN>使用经转让、涂改、出借、倒卖、出租的《餐饮服务许可证》，或者使用以其他形式非法取得的《餐饮服务许可证》从事餐饮服务的。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第三十八条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">餐饮服务提供者有下列情形之一的，由食品药品监督管理部门根据《食品安全法》第八十五条的规定予以处罚：<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（一）用非食品原料制作加工食品或者添加食品添加剂以外的化学物质和其他可能危害人体健康的物质，或者用回收食品作为原料制作加工食品；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（二）经营致病性微生物、农药残留、兽药残留、重金属、污染物质以及其他危害人体健康的物质含量超过食品安全标准限量的食品；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（三）经营营养成分不符合食品安全标准的专供婴幼儿和其他特定人群的主辅食品；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（四）经营腐败变质、油脂酸败、霉变生虫、污秽不洁、混有异物、掺假掺杂或者感官性状异常的食品；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（五）经营病死、毒死或者死因不明的禽、畜、兽、水产动物肉类及其制品；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（六）经营未经动物卫生监督机构检疫或者检疫不合格的肉类，或者未经检验或者检验不合格的肉类制品；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（七）经营超过保质期的食品；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（八）经营国家为防病等特殊需要明令禁止经营的食品；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（九）有关部门责令召回或者停止经营不符合食品安全标准的食品后，仍拒不召回或者停止经营的；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（十）餐饮服务提供者违法改变经营条件造成严重后果的。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第三十九条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">餐饮服务提供者有下列情形之一的，由食品药品监督管理部门根据《食品安全法》第八十六条的规定予以处罚：<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（一）经营或者使用被包装材料、容器、运输工具等污染的食品；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（二）经营或者使用无标签及其他不符合《食品安全法》、《食品安全法实施条例》有关标签、说明书规定的预包装食品、食品添加剂；<SPAN lang=EN-US><SPAN style="mso-spacerun: yes">&nbsp;&nbsp; </SPAN><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（三）经营添加药品的食品。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第四十条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">违反本办法第十条第一款、第十二条、第十三条第二款、第十六条第（二）、（三）、（四）、（八）、（九）项的有关规定，按照《食品安全法》第八十七条的规定予以处罚。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第四十一条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">违反本办法第二十二条第一款的规定，由食品药品监督管理部门根据《食品安全法》第八十八条的规定予以处罚。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第四十二条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">违反本办法第十六条第十项的规定，由食品药品监督管理部门根据《食品安全法》第九十一条的规定予以处罚。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">　<SPAN lang=EN-US><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第四十三条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">餐饮服务提供者违反本办法第九条第三款规定，由食品药品监督管理部门依据《食品安全法》第九十二条第二款进行处罚。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第四十四条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">本办法所称违法所得，指违反《食品安全法》、《食品安全法实施条例》等食品安全法律法规和规章的规定，从事餐饮服务活动所取得的相关营业性收入。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第四十五条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">本办法所称货值金额，指餐饮服务提供者经营的食品的市场价格总金额。其中原料及食品添加剂按进价计算，半成品按原料计算，成品按销售价格计算。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第四十六条 </SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp;</SPAN>餐饮服务食品安全监督管理执法中，涉及《食品安全法》第八十五条、第八十六条、第八十七条适用时，“情节严重”包括但不限于下列情形：<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（一）连续<SPAN lang=EN-US>12</SPAN>个月内已受到<SPAN lang=EN-US>2</SPAN>次以上较大数额罚款处罚或者连续<SPAN lang=EN-US>12</SPAN>个月内已受到一次责令停业行政处罚的；<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">（二）造成重大社会影响或者有死亡病例等严重后果的。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第四十七条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">餐饮服务提供者主动消除或者减轻违法行为危害后果，或者有其他法定情形的，应当依法从轻或者减轻处罚。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第四十八条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">在同一违反《食品安全法》、《食品安全法实施条例》等食品安全法律法规的案件中，有两种以上应当给予行政处罚的违法行为时，食品药品监督管理部门应当分别裁量，合并处罚。<SPAN lang=EN-US><SPAN style="mso-spacerun: yes">&nbsp; </SPAN><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第四十九条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">食品药品监督管理部门作出责令停业、吊销《餐饮服务许可证》、较大数额罚款等行政处罚决定之前，应当告知当事人有要求举行听证的权利。<SPAN lang=EN-US><SPAN style="mso-spacerun: yes">&nbsp;&nbsp; </SPAN><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">当事人要求听证的，食品药品监督管理部门应当组织听证。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">当事人对处罚决定不服的，可以申请行政复议或者提起行政诉讼。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第五十条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">食品药品监督管理部门不履行有关法律法规规定的职责或者其工作人员有滥用职权、玩忽职守、徇私舞弊行为的，食品药品监督管理部门应当依法对相关负责人员或者直接责任人员给予记大过或者降级的处分；造成严重后果的，给予撤职或者开除的处分；其主要负责人应当引咎辞职。<SPAN lang=EN-US> <o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt"><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><o:p>&nbsp;</o:p></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align=center><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第六章<SPAN lang=EN-US><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN>附<SPAN lang=EN-US><SPAN style="mso-spacerun: yes">&nbsp;&nbsp;&nbsp; </SPAN></SPAN>则<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第五十一条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">省、自治区、直辖市食品药品监督管理部门可以结合本地实际情况，根据本办法的规定制定实施细则。<SPAN lang=EN-US> <o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第五十二条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">国境口岸范围内的餐饮服务活动的监督管理由出入境检验检疫机构依照《食品安全法》和《中华人民共和国国境卫生检疫法》以及相关行政法规的规定实施。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">水上运营的餐饮服务提供者的食品安全管理，其始发地、经停地或者到达地的食品药品监督管理部门均有权进行检查监督。<SPAN lang=EN-US> <o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">铁路运营中餐饮服务监督管理参照本办法。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P>
                    <P class=MsoPlainText style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 32pt; mso-char-indent-count: 2.0"><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 黑体; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">第五十三条</SPAN><SPAN lang=EN-US style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体"><SPAN style="mso-spacerun: yes">&nbsp; </SPAN></SPAN><SPAN style="FONT-SIZE: 16pt; FONT-FAMILY: 仿宋_GB2312; mso-hansi-font-family: 宋体; mso-bidi-font-family: 宋体">本办法自<st1:chsdate Year="2010" Month="5" Day="1" IsLunarDate="False" IsROCDate="False" w:st="on"><SPAN lang=EN-US>2010</SPAN>年<SPAN lang=EN-US>5</SPAN>月<SPAN lang=EN-US>1</SPAN>日起</st1:chsdate>施行，卫生部<st1:chsdate Year="2000" Month="1" Day="16" IsLunarDate="False" IsROCDate="False" w:st="on"><SPAN lang=EN-US>2000</SPAN>年<SPAN lang=EN-US>1</SPAN>月<SPAN lang=EN-US>16</SPAN>日</st1:chsdate>发布的《餐饮业食品卫生管理办法》同时废止。<SPAN lang=EN-US><o:p></o:p></SPAN></SPAN></P></ucmscontent>
            </div>

        </div>

    <br><br><br><br>
    <button qid="${qid}" class="btn btn-default form-control"
            style="width:100%;height:60px;background-color:#383838;color:#fff;font-weight:bold;font-size:20px;" onclick="window.location.href = '/exerciseQuestion?qid=${qid}';">练习巩固</button>
</div>
</div>
    <script src="${pageContext.request.contextPath}/static/js/jquery-1.8.0.min.js"></script>
    <script src="${pageContext.request.contextPath}/static/js/lawPage.js"></script>
</body>
</html>
